apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:BvfDab78zkMHc6kVnsjXtjsAoRjz2lBptDtGe2WAcBl0qI26Op7A8yxvQKyyu3MZuxsvRGH+we3ugqQHCGzxETsCqs5u993Bp2BwnkINPMIT/pkH/IbfpeFgxIzpw1PSRkA/HmaT7vMwmBiL3Xmg1comVsETghRs1Wqhgc5Z3kIbC2tiOsE3PDTtRXBTomrfIKADVDIjFmqvjhDEaSO57SXZGuJs5oWGvnBPvXyXjiWlAb2ipn2AOXbdD/SRovj0P8pQoSHG5w8SnFVCuIy29Vin7MCGWLU+xFXtq0F6PEessU9n0mX//8TO18MK9/fKbtCzkMswqvjPS9lGeMck7wieH4pJ/ABX9gcabE2siWReP81CMSGrdQ/dcRXnc4Q4/S9ci6+MgzTEYJ6lTRrxAyzQQsdiAg+KQT9Uy0t/xntuLDcqIbnt1THFagSVhm28TtrEmcnCj3yUTNmMBe3724qCEKctt0XbrduhdYYI5RMyVet5TNzhyoP4AY0HOE6aKfJ/kEJRKXM/8ERNjRyTvSBpO31Zca7NvgtfUvPP+HXjB9/GHMp5Z/TAgatiHoT/MNrvYwkJOrU5f2s9hbfvMgQ/oOz3ADqjJGKNEV/Hy0hhKyhQvhQvGw/eNSx/23rvnzPvGxwpCMJsU8g7PflJnzLO,iv:H3Ah5JN5XgS63gxFoJPwakVDeZK53zP8PfkcT6BMTWQ=,tag:VjEG6GrhVE70GJ3bRnlRiA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOW81cGY1MVRSUzV4Tkt5
            UTJVeEdmK2t4UnR3RVM3eGxJMEl1MDZ4TGlrCkhKbS9IWjlxc2l4NDcrSjRGRStG
            RWVSNUd4Ly82cHZuQWU2NEF4OFNZMzAKLS0tIEZsQ3VwYnhlWkhYM2J4UVhkN3dG
            UklpN0duVXZPTC9oT3FVaERkc2pXa3cKY+kzc1WVl/66sCaQUlm+whrinNqJwRLM
            HnT4t7O7/DEI1ob2KgEsY8VrI4QYTl0pi/zcCSwFe9kyoeRdeYQ+ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T17:36:22Z"
    mac: ENC[AES256_GCM,data:Z2ud3VWR5HniN1nUl0lo6jc1nsOXDrUhP12pLRnbX8KvsWPyRxXQoULZeB3bfDutmwr395poZPe7lt2KVmVFydN8pQRhvCghTgDOjCsFgiE3KC8F+bk0r+XTe+/u2H+9SaG+N7rG7K9HLCyU8wMkhfeP2CGNmNUmZ/5Xkcd+e9M=,iv:SnzrbHSGXYQOP7jFIJCqte6IaGYbnsX58HYrl1eqieQ=,tag:B/uoogQxR6/cPx9sRRvrQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
