apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:7fH3J3z0mgfhNJpRzgvBZu2hgGwK5DpyOLlKzVuSEtOu1VhLT8+96Jl/EKIjX5ZXrqANaSbwSf6Du5FwXm5+ztKEwjpnIEaJSVKEILxoC0mFlzp/pitZpaRPhLSR+UCfgoUETKBbeZn8zXFkjlJEHpXOCaoDPa7gBBIHgYIZQcaZvm0iM36rvlAYkTRbNmJOAfdbNvfRr0gpyTDde5XuaAE0Wr/3FB+AYCvbgcdI9LeWwkWAWrUXleXdYzlp54g5EIHeUTe8/qmH5O/krwtN/c0pbkDselt5SxJwMvzRTNoco2tE7gWUA83a/AEVzsILw8wgV6Z4tZJ6ocZ4F55PTNO9sxGeByUeOkaSF3a52guSayIwPI6nlnDdqzrOtda1k2zQAZrwYOnwVAXhaRKNVG2oHV8bsQxTT/Z8htmLjFLyjQqmDqY9mAbaTJZWP6Y1W6rludkClQsAMhyOEyXAtBY08w9jCPtycwOHCzpckMX0fFLTUCgu8Fe34fSjEex6fTuoFr9BuCO/lEOzfEQawFAaaWmu41pFbJPPSUIxe1WIghUssNQFUE+ZtbJaMcZctgwqbhkc0fuZvRToZqSFPp4Fdu0YL0B73j3kCEmupuL2Md0JpIclbAnZstLcmLHJX37qNplIswMv4FVJDMuMrWBoUHV5t/7JM+9EH4W+1SkdCo8G8rkZyOL7ZQb/HvEcYBrD/nf9C2QpW5LrOoPDUhcq6y521JVrJ/rpvf3QBryHidiS52IP2Vbb8qK3GiYBs2W5OezpDY+ZJU/PhF2ASweMwFsWQwisuODzOBXAJXPKCHMm/sR1GPkw0fq152Q8t4e9uhgL3yxoCrYwgeNN/p8PkY+62zLLs/51Ni3frI30/paS4A3hasE+XyLCo/4F6OmXl0cAoXRM5JUQshfF/Fy967pjJ4jAbAqtTwCGn4XRfYwCk86VMLDga44HUFqgiaYZSD28cHNWxqbrqZAOHNf00kmWlfCUxyAqfZarYrK0zHGaJ81sUNfGRZZHTOSkIVd6Ijwokb6IzjYX31oYYBTW7rCVnaR7bG5hx1F93UL2dqOrZtKAht1UZBpnR/obvpNEYzuwmOPXRuB6XHh3nh0XNISP2iU+CQD4oPWhzmm2gVK56mVkoksmB0hGesULrj0vbZibSuiEcuVbv57K5ah6Fa/Tk5Qe/HrRgAATdMmsq2WCy1h8iJnp5gtz8Hij7sktXBp+rCOh+6IKTl1+JPY3P6M1hkpLeql5wfJQP0iC77cxRCUCHQ==,iv:8183GdZT7tUo6l2dqF0S3Nl25KULzRh5ASqafJwYZe4=,tag:mIxmz06KMBcrCIOFEs/Zfw==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdm1KT2JKSkFiVUJIeUtU
            T0lyUHA2VXNabkNEVGMzNU5lYnFldElKVkU0CmtTQ3F2dDBQS2d3dmJvU2xhTzMr
            VmlRZ3laMjNuVmhxNTIxWmpFQ3dqbVUKLS0tIG5OZHdWN1AzZjY5SVJEMTcxWTBI
            ek5nQUtVTWhWckxKUHh0ZTk3ZitEVGMKfFsk+VkhCmiKPa/OUFWeYr3q+mzTtZUh
            bXZxIONDuIrxeYHdZcw6JpvQF7zzY7Zn9jpamoNScOH/hZBUxZ3jcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T17:45:58Z"
    mac: ENC[AES256_GCM,data:VfbSChAFZNT/NLqgAa9WlAEf+bZKeO0/L4CSTHk9ekZuWix1TtWbneGPbli80e32ikOZqEqPTh++kSIoQsoLl5clR1c2974U4SvebiK3Qo74ibUf1tBLIuvLITd9nCajeYXchDEoWUa6jpNylm6nH6pJ8kQPJvCEJ/zIkyRDSQE=,iv:kqTMzSnKoSY3ka+PaU/qi/wSCid4/OMZqtZImptPwQ8=,tag:T0hgrcKFNx616s78foLAxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
