apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:gDIZsKtOovB7lVUsPAy832MqBt44giG3Xsn3AwjesS4h8NJ2bXR4wuddKVIfz7GcigePXvMbtB0UDMdtIvM34hsvIFozcEY4MIzOPPxeNKOlH9ioGOz8YyOColYLk0A8f8j3mLQSMZr91Si2zByerD/5Cxczz5tR0jS91XlWan2v+HM3i1awAaO7n6v6AgaBDlDGH9ayoQXNvvjjesIVcM1wQViP50g62b/YOFgO3NwmfTZTyT0pH00BLN12wLJb67Lfwy/Wn9xwN4Spc/TclTPGCM2VijRQf2I4HdoHhyIO5Jxq0+HTmmCE7nBqFI+PgX1uiJvBTdsWBKo5uJr55fh64BBCHppH4nSiE1u4f4jQGzoWuLe7WxwM88G3+NQkXlnnGvaLAYEJkJlADJCAmr/T2BfgDNKyI4A8fbxwhXSCq2yb8iU9hJQdlrvftCL4/zSGFjeyO6ohxnA1ib5UplMM/47AHQzHy+lnlKEciX50tzW9kIwT40uChBnod+WLWYUHwFXtGr3kKB/U5jmw87zpTDVSZfvi2cPwmaiq2zeAYf0XPIG3FGqMot8TzK+JI4CAF49NDAnDLqNjixv+bi8bidSphRlmYBhbB+kv5tqLAuKNCJgwHnKr3+y5oe8HNFE4bjFy2Wa8GRZViUvp1I/0ThPVwCeO/YO1c0dccsgl0yG7+cFU2rhbWRn3PpW4j4Sj,iv:CzBTAS7k3y3lM3z/keVsm2tkQ5e/t56UP0grDBNPkVQ=,tag:ui72cUtqfue5UFOU/VUj7A==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcXRWV3pETGFlT2U5cjdS
            OVN6Tk9heDJqTGpJVXpkWUJRSDR2YWhHbVR3CndlbEk2NFBmaFdVejRtSWh0bThR
            N3lYanV6ZFk5cWZReVpneFBmVEc4RUEKLS0tIFBVMnVpQjdkd1VUWnc0L21KTGxJ
            dFh2NEpVcERXTzhpV3IyTmhWZFlEZW8KWgJdw/DanFY9u881A08Gtir495sczpCU
            2qrRvvh8rsmUZgVM1yWGIfKSmlPPF5Z2QUe5Hgz9Ooxu8wH4w3LaXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T18:09:24Z"
    mac: ENC[AES256_GCM,data:T+scfJmaVyFHDg2kb8muAuIWzd7Uzfp7eolsKWHasj7FRvGGX2DIymsDYgWLULj71qhrGwKlirJhzwnIjISCbWkJT0Ja9V/cN0ZgCYd9YfWGUeRJyG/7CPh7ashLbZl2UCU4344MCv95hVanwXrBfi5d8yCAzygmd/p+UK3GItI=,iv:7BRiGDH+nnzrbnfJV76fjxXMO+HAoK+ie+6dsxCWEJ0=,tag:QJwDkvhh+cRZXtSUNLD6jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
