apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:5eZdadC8+R8tvBAgec/7n/onnW3wbJrJO6q3r0ot6eTEoiYpRVac7EObpwICv9Z6UaB1qHgCwMAHjy49uWRelik9C1vRRs0XMVsrXte4hzaD89qOBsMcBhqUVc5jKEOpAWG3e8hFT2vv3rrrPacokXACH4Df9nVwfdlpKe6HDq5bQvJ0oByL4iBGpsoJFRGAtTEj6E48SeQY7gwSCj2b/Oyu657GzOFWLz9Nre8TCnodgWoaCTbavlQI2qU+fhlzAH1Vih1r2eGS+03TPxLMBkdCc0FEybtWKWR5t1Td7Spo4mFlkA7/yXie0GzuHyQY8URcaVv2RvbRh2MuABErbQ7ruB1j4KEi+83RO99vC27ksXK7ixAm7QwqOecyL+FyOqzztKUNbDZM7KKNEYPSv4CHGVqd3xRvSxSmaTPjKd6xc4EfMLf2H9mNpRVcS9iQWZd9+ytjVfyZHZybM9u/bh8GVgFsvoshsgVpJ5LonUYbg9+Vrvqg8r6n,iv:pY4UySq8ggeA/xmOjsLfrvTlB6SLKHSIoDGjfxDXfMg=,tag:HqJgko0QI17qzxWBAvfKHQ==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOW81cGY1MVRSUzV4Tkt5
            UTJVeEdmK2t4UnR3RVM3eGxJMEl1MDZ4TGlrCkhKbS9IWjlxc2l4NDcrSjRGRStG
            RWVSNUd4Ly82cHZuQWU2NEF4OFNZMzAKLS0tIEZsQ3VwYnhlWkhYM2J4UVhkN3dG
            UklpN0duVXZPTC9oT3FVaERkc2pXa3cKY+kzc1WVl/66sCaQUlm+whrinNqJwRLM
            HnT4t7O7/DEI1ob2KgEsY8VrI4QYTl0pi/zcCSwFe9kyoeRdeYQ+ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T17:23:29Z"
    mac: ENC[AES256_GCM,data:pj0rzlSjAJz2PJiH+p2TWXON8AuDFWs46xZHIw5pHUFzq/2DAL9MBnjOo4ny+0Uhdb+LWj3dbuhujeXGf+79ir3ZDVROQeAzUmNYD2hwTgeNEQhO7sv/CO7Rs174rJv73wqUBl4UbF6InsrSdtnoa8eGWtlPy7+ijXO5nU65Y9E=,iv:fkDjGAtezHog+2JWnH4l1bAYUaRZJc1hMHqOY34T3LA=,tag:X+dFMdh25jlb1T30NrbnHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
