apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:s7i13AygZXQvv9YYXJBIQcnYJYin2VEDmMntDZKyrWW3L2ea/v/NwpvqZoHujCrrip5b1v5bi+mQONHHBwu5iXmEJJAuadoaIoO8UhPXyvOV6yJCb+ssWgSOw5pQUsY+gr9mP8PspZFYCB8swDigh62E2pvmIV8r9g+gU/hx14hjv8i4SU+V+MJHfi/3tCXL3akpwPnjSc0e26ZVQf4H8lCe0slezqYKyHIXfUkMQl2Xxl18garLS7z2E2ZvuSEBFdmizYxaRAIMOxMQmTRp9M/BZ1WlST8SEfURh22FXX32FJyr/jh9GU+BFnR2Q/XHpYJSfnIWxfUOmkn6rg/U/TT35iN/EUR6251EwtcmksOeNCMxPxGbtGjL0ril14MO4fejoP2ojTDBlVhF8faYiI0WHt58IOIupOsH2gQCIDD8NaBrxxLpB7o7IN0T3ka2Wy9uoLJ6KDYknYcwg/ihldSoinA6twPZQxl857xmbgYiqLRwYiNnOvHNL/fq+FxL,iv:YPebQSwjByXr2XJBVJMdz3Ze9JfqGQXvjjET9Y3q/MM=,tag:ERCnACzm9LE3SLfTun0i6g==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeFZVRWw1SHUyUno2MEx5
            RjI4cWJxMTBlc3RnVE5UUWt4K0dKSUt4bWg4CmxJdFF4ZFp6cElMalhxdm15NXZF
            NG5Yc1Y3Vmplbml6WnFiNDJsa0dEWGcKLS0tIDBXSXJ1MUVPSmdDU2h6QWo2MFNy
            NDhWTFRIVzhVWnEzaENsN0xIMlBlak0KRPBMhPrZ7rEVV53VXFp+hHmXEZiVd4DS
            C22SZsDHkbzM+1gnJYvqMWKQSfn9Bg4Ny/DqZBmAVj3P7B4aexH+zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T17:52:24Z"
    mac: ENC[AES256_GCM,data:5MhDW3QQiX+MM+ZPsY0/OC1dkxt/3WX+jCJP6ipt4CbWvJ3PMwnlb76KNvW+PmQGynkoFyjHnlyQZOmTEQMlVgsDExGG3iNNNc3jr0W8w1Xr2LonJJWLNCETwZvOZx5sPNWRO4gVZ29W/aBIsO/GRXRb3MXvvJaGUuLbY3xUiQs=,iv:4w7QvMHdTR/VE2moly+SgSoD7n+53auUjOTl77/x2Xc=,tag:mNTfXmFv1qkUQaiAXGam4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
