apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:AKqNUMZ8wVlZqnIAH1XbSkYzYGR04hTX/tqQDTxYTzxKbifRfO2rzbTuGjTqEY7tarPsTLryzsQa8Rn2qV3mh3rvbXDTHTYRl6DeGjCf89moWL/R9wqBP9Tp16wgDgLO3IRfhhdptNBAuUfghBdg6vwJXvypsqlRkclBdeS8rUNmwLLH50p5QS/hpSFBVjXXQjDLJvb1fn1vWq0h4WwnSiwI7tDppzq/Z0RYQMzIEFu7fgAmDlMzxtKmNAfUxYrM4AtQZVryMPnCJrt8DEbBCSGnYHvF1F7/Ys9MfuAPFAlOsBmhh0sdtbMG16gJbvro+724LGcFdcnGU1W9VUroC54CP2bn6LC1ngHhRDWJZvaXqX8HXnNzs6OSrhqQ4LB2rz57MJojF6C8b/I15jyIkugPOaHytN2FN3WoTpTNGWCjSTvsrAPNmkNAH8X/J5XqUCQHz3i3Ps8/7zhiZ+x593+r07vSMqSXuIbA4LSaHEb2z3fYp0y7f20z,iv:DsJEkoilW9wkU1qCEwvB3LlrNDtzt9AGbnNyT8FHJ0k=,tag:S0Aq2eCfvq/O9LlqN+snCA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOW81cGY1MVRSUzV4Tkt5
            UTJVeEdmK2t4UnR3RVM3eGxJMEl1MDZ4TGlrCkhKbS9IWjlxc2l4NDcrSjRGRStG
            RWVSNUd4Ly82cHZuQWU2NEF4OFNZMzAKLS0tIEZsQ3VwYnhlWkhYM2J4UVhkN3dG
            UklpN0duVXZPTC9oT3FVaERkc2pXa3cKY+kzc1WVl/66sCaQUlm+whrinNqJwRLM
            HnT4t7O7/DEI1ob2KgEsY8VrI4QYTl0pi/zcCSwFe9kyoeRdeYQ+ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T14:28:27Z"
    mac: ENC[AES256_GCM,data:upq1otATDD8gcd70t+kbCax91iSBmC1w6mlrTaNlpHYupT8bIF2Tu4L5TcylORAbTLU2maxOY9YbC+g3iWJl7MUS0N08U5fSCY9xb1gaVUwvsgUUvR3pyX2BCtgleGY+p5wjCmVFurVCNsGbM0NzFhRjklNDlGrIQZjUWLQqVxc=,iv:DENwJ2TQz2ITFW36c17r8IkaxEcf5ThifSLCYWG9Yqk=,tag:jL+kT6iAH8LjkPhfVGYJIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
