apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:4Apb3F4A1c4SfJShTjn2hHNvfVTy4FGPGogfjfPpbUX/wySV+F6DoCTU+hlOujo5DjGZ6x30mhJZctoWZzoBTNAxcv78jqwW/6pAJOJgcD7Nt0a9h90EyktnVTWv0nDpj3wFEXXbURV4t3fSRDNuac/yCVCFms/LcM3Daj+MUKnkz8we9q7nHzlmECKkWCw7j/Gzidz/lkkXqCoU/4Gh3tYRUkEU1zGAiFZFYcEQV1CMqWkJoAbDewOJOvUPuI9aAzIwX009KL+dmUpqVwlcSU6dJn2onen0KWb6ZrbkdsGIIYRRj0Y60BokeCXS8BAJUR+WfKaveN2Nssk1kN/b9VSAso5KCkKmkpxfG+7bYtdJyDNTGLrVDqdNEx3tO2mXDEvaZnspuK+RNgDJE6hptVKy8aqr/+xY/2JVM/A38atFXd+LKyhsgbShx1dTzBu5yWL0r6bneROapXqbwuH40O/y0Ad/JenkX21w3sm2gqK7CohwmvR4rtxE4pOlL6VbEsq4uQ6GQfOXi/YiUud3g8k7hx9oWGiP7m6go+pzjPOD81yzXy9Qv+z5FnsCixWKToBuqMUjuBZLc9rgEdvxWRMtg7ZhMOUhchu6dtGIQjFaaSisI872s+zKvoV9U9zAkAFDgVBnV5tkmC4eyacVvXi6okoo7IEbHAlQ56/7BFBYrOgVmkfMhyeq/Q3RwBqj0kaByW1ajw2iIWp1VUKm8TIVWvsLJ5bGgHV0lQdqo+RgvEN7UGJO1KVz4x4cnSgWR2TcDdcJ8Idj6wi0QlmUNdEidRoKYtojeJKpvXB7W0cCb1KJG3BOv6GGFt3VbeNheGEMdzOLD2Bn+VEmzVZluTrQW5cqBz7MwUju/bZNfRfjFHCU0/39qkh/NBEAiAlhrysq8W64G2W1yN+z1EkjQqnG/rPaAAk42q9Mcgc5d7UTEaHeLaMIebpXEKSexrZp24rkrPvvyk1tquGfXXkPFdA+CP3iiDCF,iv:j0tLo2YLiN/wLQWCP6a/c4krlXdlIT1pr9PZV27ccFk=,tag:f3euWYajFsiwoyAtN0lSFA==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzY0gxUzhJQzNKaGFYWm4r
            RUF2VE5lRXI3NFVKa1ZvS2xoZWJna3l3dEFVClR2MTVmL1pLTTdyU25pTlNEeWNK
            VWVQMjFFY0tYUGQ3YjR6Vml6eGtBeGcKLS0tIG5ucElGaGptdGViZzdIWnpGaTJG
            ZW5peklHZm5zL2JXZ1NMRmoxTWFVb2sK2Uotj9i46ENSTCjTBAjfMW6yfd3ywLta
            COFeWer/EAnpnjnz3izMvtbCp/XXXkJZhrcBQat2yZGMDEvMJfb0qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T18:11:24Z"
    mac: ENC[AES256_GCM,data:wGncqniqZcgOMj72I3ikYW7YV6kUpEMIkVNbA22qyqwiMVsS7NE3mPNGhL2zraLL9yQQpMdJhETf1sZnBFkPaNth3UgyeC5p4N7a+QOsJ8HAp1FZRqpgy7Q00EfOB8F3RyIvNYf+wxqTxaipJIXytT5J3XAlfCIIpzB93ygUhBo=,iv:4uov1dBrUTy1dz/zmmCNcpWixXjTWgmsj/LqPwksCY0=,tag:PRm7POwCnsyBTKRILzxtiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
