apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: scolx-frontend
  namespace: scolx-demo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`demo.scolx.com`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: traefik
      services:
        - name: scolx-frontend
          port: web
  tls:
    certResolver: letsencrypt
