apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scolx-demo
resources:
  - namespace.yaml
  - deploy-frontend.yaml
  - svc-frontend.yaml
  - deploy-backend.yaml
  - svc-backend.yaml
  - ingress-frontend.yaml
