apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scolx
resources:
  - namespace.yaml
  - deploy-frontend.yaml
  - svc-frontend.yaml
  - deploy-backend.yaml
  - svc-backend.yaml
  - ingress-frontend.yaml
  - cnpg-cluster.yaml
  - cnpg-scolx-db.yaml
  - helmrelease-pgadmin.yaml
  - cronjob-reminders.yaml
  - cronjob-rt-cleanup.yaml
  - cronjob-stripe-cleanup.yaml
  - servicemonitor.yaml
  - helmrelease-minio.yaml
  - svc-mathapi.yaml
  - deploy-mathapi.yaml