apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yaml
  - plex-pvc.yaml
  - helmrelease-jellyfin.yaml
  - ingressroute-jellyfin.yaml
  - helmrelease-jellyseerr.yaml
  - pvc-qbit.yaml
  - helmrelease-qbittorrent.yaml
  - helmrelease-radarr.yaml
  - helmrelease-sonarr.yaml
  - helmrelease-prowlarr.yaml
  - helmrelease-flaresolverr.yaml
  - servicemonitor-media.yaml
