apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns
    namespace: traefik
type: Opaque
stringData:
    CF_DNS_API_TOKEN: ENC[AES256_GCM,data:9xGpQHWllDhUQDC7G3/8U/VI0Zs4VPMw9PNNbsN53woe/nOCQRJeuQ==,iv:plsoj1+ooky+V5WDIYHPjNwAR/X6xdpO2ILqK7GRMzM=,tag:NzE9HyK+z7QfoT4mAUH5Og==,type:str]
sops:
    age:
        - recipient: age1lkt8h48rt7addnx0a4fjjmlul03xt32wdwh832d5k6xn7x4h24msgs05kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdmt1enEyNTBJdmdtUkts
            YWVVTG01dEpLbnV5VkxBcVRScHR2QXIraUNBCk1CclA2eFFMMFR4bkFpcE9ld2RQ
            ejBvNFUwOGJ1ZVJ4bFJGMFJIUEt5a00KLS0tIHNQcjVuK2lIcjJxbC90VkdKQVE0
            bmQyM3JPS0hJYU1tcGVSTEVaS3Jlc0EKjpHP3UVbaPwgG9ThT6aVa1y7GRXP9uHA
            DF2JOJNHBodGNGW8QVd5S3/ayLTTLPQKzLC38xhahxsXsZk2MXlTaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-03T18:57:20Z"
    mac: ENC[AES256_GCM,data:34KawB3nuMiDJ6+8DZKrm8LAjZdb7tm7qL8vwVf0Ogm1VJzZawCiMZNbGcYT1ttOFfXQYTpijXKy47gQw9W+D0TXnmHuHoJ24Let9NTuVLoc0DY5YDj0jRxcIZn8eQ2JyXc+uws993pzU6Z8xSX7bsF+x57dKJO78sdMy9eQeRQ=,iv:ovI4o+NZjM2Pxl7jITGjgaDwbfK4Ed9dM/DKMLskw+w=,tag:qvQL25vbSIM5pHQxGNsY1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
