apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matrix-wellknown
  namespace: matrix
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cherkaoui.ch`) && PathPrefix(`/.well-known/matrix`)
      kind: Rule
      services:
        - name: matrix-well-known-delegation
          port: 80
  tls:
    certResolver: letsencrypt
