apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: matrix-synapse
  namespace: matrix
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`matrix.cherkaoui.ch`) && (PathPrefix(`/_matrix/client/`) && (PathRegexp(`^/_matrix/client/[^/]+/login`) || PathRegexp(`^/_matrix/client/[^/]+/logout`) || PathRegexp(`^/_matrix/client/[^/]+/refresh`)))
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: traefik
      services:
        - name: matrix-matrix-authentication-service
          port: 8080
    - match: Host(`matrix.cherkaoui.ch`)
      kind: Rule
      middlewares:
        - name: security-headers
          namespace: traefik
      services:
        - name: matrix-synapse
          port: 8008
  tls:
    certResolver: letsencrypt
