apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - namespace.yaml
  - helmrelease-matrix.yaml
  - ingressroute-matrix.yaml
  - ingressroute-element.yaml
  - ingressroute-auth.yaml
  - ingressroute-rtc.yaml
  - ingressroute-admin.yaml
  - ingressroute-wellknown.yaml
  - service-rtc-loadbalancer.yaml
